In [3]:
import numpy as np
import pandas as pd
print('Khai bao thu vien thanh cong')

Khai bao thu vien thanh cong

In [4]:
from google.colab import drive
drive.mount('/content/grive')

Mounted at /content/grive

In [ ]:
df=pd.read_csv('/content/grive/My Drive/My Drive/codegym/Bai 1/FoodPrice_in_Turkey.csv',header=0,encoding='ISO-8859-1')
df

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7381 entries, 0 to 7380
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Place        7381 non-null   object
 1   ProductId    7381 non-null   int64
 2   ProductName  7381 non-null   object
 3   UmId         7381 non-null   int64
 4   UmName       7381 non-null   object
 5   Month        7381 non-null   int64
 6   Year         7381 non-null   int64
 7   Price        7381 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 461.4+ KB

In [ ]:
print(df.shape)
print("So dong la: ",df.shape[0],"\n","So cot la: ",df.shape[1])

(7381, 8)
So dong la:  7381
 So cot la:  8

In [ ]:
df['cot moi']=np.NaN
df

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price,cot moi
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,NaN
...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,NaN
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,NaN

In [ ]:

df

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price,Chiet khau (%),cot moi
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,10,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,16,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,12,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,17,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,2,NaN
...,...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,3,NaN
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,18,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,19,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,2,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,18,NaN

In [7]:
dt=pd.read_excel('/content/grive/My Drive/tài liệu/house_price_dống-da.xlsx')
dt

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,title,address,area,price,postDate,land_certificate,house_direction,balcony_direction,toilet,bedroom,floor,type_of_land,street_name,ward_name,district_name,city_name,lat,long
0,Bán nhà Trần Quang Diệu mới coong đẹp 50m2x6 t...,"Đường Trần Quang Diệu, Phường Trung Liệt, Đốn...",50.0,14700.0,2021-01-01,Sổ đỏ,NaN,NaN,4.0,6.0,6.0,Bán nhà riêng\n,Đường Trần Quang Diệu,Phường Trung Liệt,Quận Đống Đa,Thành phố Hà Nội,21.015698,105.824583
1,Bán nhà mặt phố Tây Sơn - 6 tầng. Kinh doanh t...,"Đường Tây Sơn, Phường Trung Liệt, Đống Đa, Hà...",35.0,12500.0,2021-02-19,Sổ đỏ,NaN,NaN,NaN,NaN,6.0,Bán nhà mặt phố\n,Phố Trung Liệt,Phường Trung Liệt,Quận Đống Đa,Thành phố Hà Nội,21.008930,105.824105
2,Bán nhà số 36 Đoàn Kết - phố Khâm Thiên - Đống...,"Số 36 Đoàn Kết, Phố Khâm Thiên, Phường Thổ Qu...",57.0,4200.0,2021-03-10,Sổ đỏ,Nam,Nam,3.0,8.0,4.0,Bán nhà riêng\n,Phố Khâm Thiên,Phường Khâm Thiên,Quận Đống Đa,Thành phố Hà Nội,21.025208,105.833111
3,Bán nhà 6 tầng mới kinh doanh mặt ngõ 1194 Đườ...,"Ngõ 1194, Đường Láng, Phường Láng Thượng, Đố...",62.0,11000.0,2021-03-13,Sổ đỏ,Đông,Đông-Nam,6.0,5.0,6.0,Bán nhà riêng\n,Đường Láng Thượng,Phường Láng Thượng,Quận Đống Đa,Thành phố Hà Nội,21.025379,105.801011
4,"Bán nhà mặt phố Thái Hà 70m2, 5 tầng, 4.5m mặt...","Phố Thái Hà, Phường Trung Liệt, Đống Đa, Hà Nội",70.0,36000.0,2021-03-13,Sổ đỏ,NaN,NaN,NaN,6.0,5.0,Bán nhà mặt phố\n,Phố Trung Liệt,Phường Trung Liệt,Quận Đống Đa,Thành phố Hà Nội,21.009239,105.824230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"Bán nhà mặt phố Yên Lãng, Đống Đa, 65m2, 5T, 1...","Đường Yên Lãng, Phường Láng Hạ, Đống Đa, Hà...",65.0,17500.0,2021-05-09,Sổ đỏ,NaN,NaN,NaN,6.0,5.0,Bán nhà mặt phố\n,Đường Yên Lãng,Phường Láng Hạ,Quận Đống Đa,Thành phố Hà Nội,21.011495,105.816666
996,"Bán nhà 5 tầng đep MP Yên Lãng giá rẻ, DT 60m2...","Đường Yên Lãng, Phường Trung Liệt, Đống Đa, ...",60.0,17500.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,Bán nhà mặt phố\n,Phố Trung Liệt,Phường Trung Liệt,Quận Đống Đa,Thành phố Hà Nội,21.011495,105.816666
997,MẶT PHỐ XÃ ĐÀN - KINH DOANH ĐỈNH CAO - 6 TẦNG ...,"Phố Xã Đàn, Phường Ô Chợ Dừa, Đống Đa, Hà Nội",45.0,24800.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,Bán nhà mặt phố\n,Đường Ô Chợ Dừa,Phường Ô Chợ Dừa,Quận Đống Đa,Thành phố Hà Nội,21.016106,105.832157
998,"Bán nhà mặt hồ Văn Chương, Đống Đa 33m2, 6 tần...","Hồ Văn Chương, Phường Văn Chương, Quận Đống Đa...",178.0,8100.0,2021-01-01,Sổ đỏ,NaN,NaN,4.0,3.0,NaN,Bán nhà riêng,Đường Hồ Văn Chương,Phường Văn Chương,Quận Đống Đa,Thành phố Hà Nội,21.021345,105.833122
999,"Bán nhà 5 tầng MP Chùa Bộc hạ giá sốc, tử 58,6...","Phố Chùa Bộc, Phường Khương Thượng, Đống Đa, ...",107.0,45000.0,2021-05-09,Sổ đỏ,NaN,NaN,NaN,NaN,5.0,Bán nhà mặt phố\n,Phố Khương Thượng,Phường Khương Thượng,Quận Đống Đa,Thành phố Hà Nội,21.009123,105.824428